###
POST {{content_host}}/content/course/list?pageNo=2&pageSize=10
Content-Type: application/json

{
  "auditStatus": "202002",
  "courseName": "1",
  "publishStatus": "203001"
}

<> 2023-03-16T094248.200.json
